#!/bin/bash

# Set xserver to use modesetting or nvidia

OUTPUT1="eDP-1-1"
OUTPUT2="HDMI-0"

X11_CONF=/etc/X11/xorg.conf.d/20-current.conf
X11_INIT=~/.xinitrc

GEN_MSG="Generated by switch GPU script"

DISPLAYLINK='# '$GEN_MSG'

Section "Device"
  Identifier  "DisplayLink"
  Driver      "modesetting"
  Option      "PageFlip" "false"
EndSection'

NVIDIA='# '$GEN_MSG'

Section "ServerLayout"
    Identifier     "layout"
    Screen      0  "nvidia"
EndSection

Section "Module"
    Load           "modesetting"
EndSection

Section "Device"
    Identifier     "nvidia"
    Driver         "nvidia"
    BusID          "PCI:1:0:0"
EndSection

Section "Screen"
    Identifier     "nvidia"
    Device         "nvidia"

    # Needs if HDMI output is disconnected
    Option         "AllowEmptyInitialConfiguration"
EndSection'

XINIT='# '$GEN_MSG'

xrandr --setprovideroutputsource 1 0
xrandr --output '$OUTPUT1' --auto --output '$OUTPUT2' --auto --above '$OUTPUT1'
i3'

if [ $# -ne 1 ]; then
  echo "Usage: $0 [modesetting|nvidia]"
  exit 1
fi

COLOR_INFO='\033[0;32m'
COLOR_NONE='\033[0m'

case "$1" in
"modesetting")
  GLX="/usr/lib/mesa-diverted"
  echo -e "${COLOR_INFO}Create file $X11_CONF:${COLOR_NONE}"
  echo "--------------------"
  echo "$DISPLAYLINK" | sudo tee $X11_CONF
  echo "--------------------"
  echo

  if [ -f $X11_INIT ]; then
    echo -e "${COLOR_INFO}Remove file $X11_INIT:${COLOR_NONE}"
    rm $X11_INIT
  fi
  ;;
"nvidia")
  GLX="/usr/lib/nvidia"
  echo -e "${COLOR_INFO}Create file $X11_CONF:${COLOR_NONE}"
  echo "--------------------"
  echo "$NVIDIA" | sudo tee $X11_CONF
  echo "--------------------"
  echo

  echo -e "${COLOR_INFO}Create file $X11_INIT:${COLOR_NONE}"
  echo "--------------------"
  echo "$XINIT" | tee $X11_INIT
  echo "--------------------"
  echo
  ;;
*)
  echo "Usage: $0 [modesetting|nvidia]"
  exit 2
  ;;
esac

if [ "$1" != "modesetting" -a "$1" != "nvidia"  ]; then
  echo "Usage: $0 [modesetting|nvidia]"
  exit 2
fi

# Manual select if need
# sudo update-glx --config glx

#echo "Update GLX library"
#sudo update-glx --set glx $GLX
glxinfo|egrep "OpenGL vendor|OpenGL renderer*"
